spring.application.name=mandala


spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bismtlnejcdktxmoudjh
spring.datasource.password=12345678mandala
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# # === AWS S3 CONFIG ===
# aws.access-key=AKIA523CUSKL2ZNK3JIR

# aws.secret-key=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
# aws.region=eu-north-1
# aws.bucket-name=mandalaproducts

supabase.storage.url=https://bismtlnejcdktxmoudjh.supabase.co/storage/v1
supabase.api.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpc210bG5lamNka3R4bW91ZGpoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MzAwNTMxNCwiZXhwIjoyMDU4NTgxMzE0fQ.TOlOLSRRsRaqlGcS4Pa3zAYqC-VPoNA2dDl6KhzVW2w
supabase.bucket.name=product-images
supabase.jwt.jwk-set-uri=https://bismtlnejcdktxmoudjh.supabase.co/auth/v1/keys

# jwt.secret=4ja93KRJB2ZuYXS26bO0slaPFCfA8evTOp9iKdLXk0se0DOA6H7LBF4TM5PjXCfACINLVs/6dUpAd4hdRCu9/A==

# jwt.secret=4d434dd3408911b8729fe2e1d7177f330936b59c12b2147ca20f440b1d67d3387eba25026f69edb9883492e770d68e756b6a5e0f8aef6c14a6c3d4c62ecea502

jwt.secret=a89ddb16964f7687b9abe177429465354fe47f6923a83bb16c9f72928bd04e639048e41c529ee2fcb63d5bb19c108ab2a2df645e12c9b2278ab74a386817a5e9
