spring.application.name=mandala


spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.enioqxadgpshpqunzaie
spring.datasource.password=PCpsjTjbGfT3NI72
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=a89ddb16964f7687b9abe177429465354fe47f6923a83bb16c9f72928bd04e639048e41c529ee2fcb63d5bb19c108ab2a2df645e12c9b2278ab74a386817a5e9